### ISSUE TITLE
Encapsulate authorization of in googleio.py

### ISSUE THREAD

**Issue by ipendlet** [darkreactions/ESCALATE_Capture#39]
authorization code in `googleio.py` is top level code. 

This is holdover from old scripting that hasn't yet been updated for production

move to function call

**Comment by miketynes** [comment]
@ipendlet  @aadharna 

The primary challenge is related to this line: https://github.com/darkreactions/ESCALATE_Capture/blob/447e9d0d33d2c4c6519a8131b025bc5ea36d7722/capture/googleapi/googleio.py#L41
Which creates a `pydrive.drive.GoogleDrive` object. This object is then referenced in all of the module-level functions. 

This may be a moment where OOP can shine: we can have our own GoogleIO handler class which has a GoogleDrive member variable that only gets created at `__init__` time. 

How does this sound to you guys? 

Note: we probably shouldn't spend too much time on this since we want to replace the google drive with a proper backend that is accessed through a web-interface.

**Comment by ipendlet** [comment]
closed alongside #43
